# From /g/, https://pastebin.com/Vi47rVcE, train_gpt_tts_unified.yml (https://pastebin.com/Sce7Sw7q)

#### general settings
# Notes:
name: train_gpt_tts_unified_large_doubled_pos
use_tb_logger: true
gpu_ids: [0,1,2,3,4,5,6,7]
start_step: 0
fp16: false
checkpointing_enabled: true
wandb: true
wandb_project_name: train_gpt_tts
wandb_run_name: unified_with_bpe_large_diverse

datasets:
  train:
    name: clips
    n_workers: 1
    batch_size: 1024
    mode: fast_paired_voice_audio
    sample_rate: 22050
    path: [/y/libritts/train-other-500/transcribed-oco-realtext.tsv,
           /y/libritts/train-clean-100/transcribed-oco-realtext.tsv,
           /y/libritts/train-clean-360/transcribed-oco-realtext.tsv,
           #/y/clips/podcasts-0/transcribed-oco.tsv,
           /y/clips/books1/transcribed-oco.tsv,
           /y/clips/books2/transcribed-oco.tsv,
	       /y/bigasr_dataset/hifi_tts/transcribed-oco-realtext.tsv,
           #/y/clips/podcasts-0/transcribed-oco.tsv,
           #/y/clips/podcasts-1/transcribed-oco.tsv,
    ]
    max_wav_length: 551250
    max_text_length: 350
    #max_wav_length: 255995
    #max_text_length: 120
    load_conditioning: true
    num_conditioning_candidates: 3
    conditioning_length: 132300
    use_bpe_tokenizer: true
  val:
    name: mass_test
    n_workers: 1
    batch_size: 16
    mode: paired_voice_audio
    sample_rate: 22050
    path: [/y/libritts/test-clean_list.txt]
    fetcher_mode: [libritts]
    max_wav_length: 286715  # max_mel_tokens*1024 - 5
    max_text_length: 200
    load_conditioning: true
    num_conditioning_candidates: 3
    conditioning_length: 132300
    needs_collate: false
    use_bpe_tokenizer: true


networks:
  gpt:
    type: generator
    which_model_G: unified_voice2
    kwargs:
      # These are both intentionally greater than the amount that is actually trained on, for breathing room in the future.
      max_text_tokens: 402
      #max_text_tokens: 200
      max_mel_tokens: 604
      #max_mel_tokens: 300
      max_conditioning_inputs: 2
      layers: 30
      model_dim: 1024
      heads: 16
      checkpointing: true
      train_solo_embeddings: false  # This is forced because of DDP
      average_conditioning_embeddings: true

#### path
path:
  #pretrain_model_gpt: ../experiments/train_gpt_tts_unified_large_doubled_pos/models/4500_gpt_ema.pth
  strict_load: true
  resume_state: ../experiments/train_gpt_tts_unified_large_doubled_pos/training_state/8500.state

steps:
  gpt_train:
    training: gpt
    loss_log_buffer: 500

    # Generally follows the recipe from the DALLE paper.
    optimizer: adamw_zero
    optimizer_params:
      lr: !!float 1e-5
      weight_decay: !!float 1e-2
      beta1: 0.9
      beta2: 0.96
    clip_grad_eps: 4

    injectors:
      paired_to_mel:
        type: torch_mel_spectrogram
        mel_norm_file: ../experiments/clips_mel_norms.pth
        in: wav
        out: paired_mel
      paired_cond_to_mel:
        type: for_each
        subtype: torch_mel_spectrogram
        mel_norm_file: ../experiments/clips_mel_norms.pth
        in: conditioning
        out: paired_conditioning_mel
      to_codes:
        type: discrete_token
        in: paired_mel
        out: paired_mel_codes
      paired_fwd_text:
        type: generator
        generator: gpt
        in: [paired_conditioning_mel, padded_text, text_lengths, paired_mel_codes, wav_lengths, true]
        out: [loss_text_ce, loss_mel_ce, logits]
    losses:
      text_ce:
        type: direct
        weight: .01
        key: loss_text_ce
      mel_ce:
        type: direct
        weight: 1
        key: loss_mel_ce


train:
  niter: 500000
  warmup_iter: -1
  mega_batch_factor: 16
  ema_rate: .999
  val_freq: 500

  default_lr_scheme: MultiStepLR
  gen_lr_steps: [ 10000, 20000, 40000 ]
  lr_gamma: 0.2
  warmup_steps: 500
  force_lr: !!float 4e-6

eval:
  pure: true

logger:
  print_freq: 5
  save_checkpoint_freq: 250
  visuals: []
  is_mel_spectrogram: true
  visual_debug_rate: 100
