# Notes:
#### general settings
name: train_diffusion
use_tb_logger: true
model: extensibletrainer
distortion: sr
scale: 1
gpu_ids: [0]
start_step: 0
checkpointing_enabled: true
grad_scaler_enabled: false
fp16: false
wandb: false

datasets:
  train:
    name: clips
    n_workers: 2
    batch_size: 512
    mode: paired_voice_audio
    sample_rate: 22050
    path: [path/to/dataset1, path/to/dataset2, ...]
    fetcher_mode: ['lj', 'lj', ...']
    max_wav_length: 220500
    max_text_length: 160
    load_conditioning: true
    num_conditioning_candidates: 2
    conditioning_length: 102400
    needs_collate: false
    use_bpe_tokenizer: true
    load_aligned_codes: false
  val:
    name: mass_test
    n_workers: 1
    batch_size: 6
    mode: paired_voice_audio
    sample_rate: 22050
    path: [path/to/dataset1, path/to/dataset2, ...]
    fetcher_mode: ['lj', 'lj', ...']
    max_wav_length: 220500
    max_text_length: 160
    load_conditioning: true
    num_conditioning_candidates: 2
    conditioning_length: 102400
    needs_collate: false
    use_bpe_tokenizer: true
    load_aligned_codes: false

networks:
  generator:
    type: generator
    which_model_G: diffusion_tts_flat
    kwargs:
      model_channels: 1024
      num_layers: 10
      in_channels: 100
      out_channels: 200
      in_latent_channels: 1024
      in_tokens: 8193
      dropout: .1
      use_fp16: false
      num_heads: 16
      layer_drop: 0
      unconditioned_percentage: 0.15

#### path
path:
  strict_load: true

steps:
  generator:
    training: generator
    loss_log_buffer: 2000
    step_outputs: [loss]

    optimizer: adamw
    optimizer_params:
      lr: !!float 1e-5
      weight_decay: 0.001
      beta1: 0.9
      beta2: 0.999
    clip_grad_eps: 1.0

    injectors:
      to_mel:
        type: torch_mel_spectrogram
        mel_norm_file: ../recipes/tortoise-tts/clips_mel_norms.pth
        in: wav
        out: mel
      resample_wav:
        type: audio_resample
        in: wav
        out: wav_for_vocoder
        input_sample_rate: 22050
        output_sample_rate: 24000
      tacotron_mel:
        type: mel_spectrogram
        mel_fmax: 12000
        sampling_rate: 24000
        n_mel_channels: 100
        # Only normalize the MEL target, because the diffuser specifically cares about it.
        do_normalization: true
        in: wav_for_vocoder
        out: target_mel
      resample_cond:
        type: for_each
        subtype: audio_resample
        input_sample_rate: 22050
        output_sample_rate: 24000
        in: conditioning
        out: conditioning_for_vocoder
      cond_to_mel:
        type: for_each
        subtype: mel_spectrogram
        mel_fmax: 12000
        sampling_rate: 24000
        n_mel_channels: 100
        in: conditioning_for_vocoder
        out: cond_mel
      produce_latents:
        type: gpt_voice_latent
        gpt_path: ../recipes/tortoise-tts/autoregressive.pth
        in: wav
        conditioning_clip: conditioning
        text: padded_text
        text_lengths: text_lengths
        input_lengths: wav_lengths
        out: gpt_latent
      diffusion:
        type: gaussian_diffusion
        in: target_mel
        generator: generator
        beta_schedule:
          schedule_name: linear
          num_diffusion_timesteps: 4000
        diffusion_args:
          model_mean_type: epsilon
          model_var_type: learned_range
          loss_type: mse
        sampler_type: uniform
        model_input_keys:
          aligned_conditioning: gpt_latent
          conditioning_input: cond_mel
          return_code_pred: true
        extra_model_output_keys: [mel_pred]
        out: loss
        out_key_vb_loss: vb_loss
        out_key_x_start: x_start_pred
    losses:
      diffusion_loss:
        after: 500
        type: direct
        weight: 1
        key: loss
      var_loss:
        after: 500
        type: direct
        weight: 1
        key: vb_loss
      mel_surrogate:
        type: pix
        weight: 1
        criterion: l2
        real: target_mel
        fake: mel_pred

train:
  niter: 500000
  warmup_iter: 0  # This needs to be removed since it merely duplicates warmup_steps.
  mega_batch_factor: 4
  val_freq: 500
  sort_key: wav_lengths
  auto_collate: true

  # Default LR scheduler options
  default_lr_scheme: MultiStepLR
  gen_lr_steps: [ 60000 ]
  lr_gamma: 0.2
  warmup_steps: 1000

logger:
  print_freq: 5
  save_checkpoint_freq: 250
